"""clinicas e profissionais

Revision ID: 5d01a7c05380
Revises: 8179ed4ee637
Create Date: 2026-10-06 14:50:56.540878
"""
from alembic import op
import sqlalchemy as sa


revision = '5d01a7c05380'
down_revision = '8179ed4ee637'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('nome_busca', sa.String(length=80), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_especialidades_nome_busca'), 'especialidades', ['nome_busca'], unique=False)
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nome_busca', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('abertura', sa.Time(), nullable=False),
    sa.Column('fechamento', sa.Time(), nullable=False),
    sa.Column('dias_funcionamento', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('abertura < fechamento', name='ck_unidades_horario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidades_nome_busca'), 'unidades', ['nome_busca'], unique=False)
    op.create_table('profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nome_busca', sa.String(length=120), nullable=False),
    sa.Column('conselho', sa.String(length=10), nullable=False),
    sa.Column('registro_numero', sa.String(length=20), nullable=False),
    sa.Column('registro_uf', sa.String(length=2), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conselho', 'registro_numero', 'registro_uf', name='uq_profissionais_registro'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_profissionais_nome_busca'), 'profissionais', ['nome_busca'], unique=False)
    op.create_table('tipos_consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('duracao_min', sa.Integer(), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.CheckConstraint('duracao_min BETWEEN 15 AND 120 AND duracao_min %% 5 = 0', name='ck_tipos_duracao'),
    sa.CheckConstraint('preco_centavos >= 0', name='ck_tipos_preco'),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_consulta_especialidade_id'), 'tipos_consulta', ['especialidade_id'], unique=False)
    op.create_table('profissional_especialidade',
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profissional_id', 'especialidade_id')
    )
    op.create_table('profissional_unidade',
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profissional_id', 'unidade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profissional_unidade')
    op.drop_table('profissional_especialidade')
    op.drop_index(op.f('ix_tipos_consulta_especialidade_id'), table_name='tipos_consulta')
    op.drop_table('tipos_consulta')
    op.drop_index(op.f('ix_profissionais_nome_busca'), table_name='profissionais')
    op.drop_table('profissionais')
    op.drop_index(op.f('ix_unidades_nome_busca'), table_name='unidades')
    op.drop_table('unidades')
    op.drop_index(op.f('ix_especialidades_nome_busca'), table_name='especialidades')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
