"""usuarios e tokens

Revision ID: 8179ed4ee637
Revises: 
Create Date: 2026-10-06 14:43:06.718680
"""
from alembic import op
import sqlalchemy as sa


revision = '8179ed4ee637'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('tentativas_falhas', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("perfil IN ('paciente', 'profissional', 'recepcao', 'admin')", name='ck_usuarios_perfil'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tokens_renovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_tokens_renovacao_usuario_id'), 'tokens_renovacao', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_renovacao_usuario_id'), table_name='tokens_renovacao')
    op.drop_table('tokens_renovacao')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
