"""agenda e consultas

Revision ID: c8aaa33475a5
Revises: 5d01a7c05380
Create Date: 2026-10-06 14:55:25.013693
"""
from alembic import op
import sqlalchemy as sa


revision = 'c8aaa33475a5'
down_revision = '5d01a7c05380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'unidade_id', name='uq_feriados_data_unidade')
    )
    op.create_index(op.f('ix_feriados_data'), 'feriados', ['data'], unique=False)
    op.create_table('bloqueios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.CheckConstraint('inicio < fim', name='ck_bloqueios_intervalo'),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloqueios_profissional_id'), 'bloqueios', ['profissional_id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('tipo_consulta_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.Column('remarcacoes', sa.Integer(), nullable=False),
    sa.Column('consulta_origem_id', sa.Integer(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('marcada', 'confirmada', 'em_atendimento', 'realizada', 'cancelada_paciente', 'cancelada_clinica', 'faltou')", name='ck_consultas_status'),
    sa.CheckConstraint('inicio < fim', name='ck_consultas_intervalo'),
    sa.CheckConstraint('remarcacoes BETWEEN 0 AND 2', name='ck_consultas_remarcacoes'),
    sa.ForeignKeyConstraint(['consulta_origem_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['tipo_consulta_id'], ['tipos_consulta.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_inicio'), 'consultas', ['inicio'], unique=False)
    op.create_index(op.f('ix_consultas_paciente_id'), 'consultas', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_consultas_profissional_id'), 'consultas', ['profissional_id'], unique=False)
    op.create_index(op.f('ix_consultas_unidade_id'), 'consultas', ['unidade_id'], unique=False)
    op.create_index('uq_consultas_profissional_inicio_ativa', 'consultas', ['profissional_id', 'inicio'], unique=True, postgresql_where=sa.text("status IN ('marcada', 'confirmada', 'em_atendimento')"))
    op.create_table('grade_horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 0 AND 6', name='ck_grade_dia'),
    sa.CheckConstraint('hora_inicio < hora_fim', name='ck_grade_intervalo'),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grade_horarios_profissional_id'), 'grade_horarios', ['profissional_id'], unique=False)
    op.create_table('historico_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('de_status', sa.String(length=20), nullable=True),
    sa.Column('para_status', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_consulta_id'), 'historico_status', ['consulta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historico_status_consulta_id'), table_name='historico_status')
    op.drop_table('historico_status')
    op.drop_index(op.f('ix_grade_horarios_profissional_id'), table_name='grade_horarios')
    op.drop_table('grade_horarios')
    op.drop_index('uq_consultas_profissional_inicio_ativa', table_name='consultas', postgresql_where=sa.text("status IN ('marcada', 'confirmada', 'em_atendimento')"))
    op.drop_index(op.f('ix_consultas_unidade_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_profissional_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_paciente_id'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_inicio'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_bloqueios_profissional_id'), table_name='bloqueios')
    op.drop_table('bloqueios')
    op.drop_index(op.f('ix_feriados_data'), table_name='feriados')
    op.drop_table('feriados')
    # ### end Alembic commands ###
